default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Abby2020#

development:
  <<: *default
  database: debug_me_development

test:
  <<: *default
  database: debug_me_test

production:
  <<: *default
  database: Voting_System_production
  username: Voting_System
  password: <%= ENV["VOTING_SYSTEM_DATABASE_PASSWORD"] %>
